### ISSUE TITLE
[BUG] subtitle_font_size和subtitle_margin_v未赋值

### ISSUE THREAD

**Issue by lululutx** [timerring/bilive#144]
最新版本下

`
2024-12-21 02:16:43 There is no file recorded. Check again in 120 seconds.
Processing /home/lulu/Projects/bilive/Videos/14709735/14709735_20241221-02-11-26.mp4...
The video resolution is 1280x720
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/lulu/Projects/bilive/src/burn/scan.py", line 62, in <module>
    process_folder_append(room_folder)
  File "/home/lulu/Projects/bilive/src/burn/scan.py", line 49, in process_folder_append
    render_video_only(file)
  File "/home/lulu/Projects/bilive/src/burn/only_render.py", line 48, in render_video_only
    render_video(original_video_path, format_video_path, subtitle_font_size, subtitle_margin_v)
UnboundLocalError: local variable 'subtitle_font_size' referenced before assignment
`

**Comment by timerring** [comment]
这个我也在排查，初步的判断是一个冗余的异常，视频实际上已经处理完成在上传队列了，但是处理队列里又读取了一次原视频文件名称，并且原文件名称对应的文件名已经不存在了，所以没读到内容，顺序执行下来就处理下一个视频去了。

所以这个应该不影响正常使用，之后我添加个判断文件不存在直接返回就行。
